name: gg_log
description: Helpers for logging, e.g. a GgLog typedef used in many of our projects.
version: 1.0.1
repository: https://github.com/inlavigo/gg_log.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  gg_args: ^1.1.3
  gg_process: ^1.0.7
  path: ^1.8.0

dev_dependencies:
  gg_capture_print: ^1.0.3
  gg_install_gg: ^1.0.1
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
